# Generated by Django 2.2.1 on 2019-07-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_model', models.CharField(max_length=30, verbose_name='name of truck model')),
                ('truck_capacity', models.IntegerField(default=100, verbose_name='cargo capacity of the truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_weight', models.IntegerField(default=100, verbose_name='cargo weight')),
                ('truck_id', models.CharField(max_length=30, unique=True, verbose_name='truck id')),
                ('truck_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_app.TruckModel', verbose_name='working truck')),
            ],
        ),
    ]
